#+TITLE: 杨澄甫口述-太极拳说十要
#+LANGUAGE: cn
#+DESCRIPTION: 杨澄甫口述-太极拳说十要
#+KEYWORDS:  杨澄甫 太极拳
#+STYLE: <link rel="stylesheet" href="../css/default.css" type="text/css"/>

* 虚灵顶劲
顶劲者，头容正直，神贯于顶也。不可用力，用力则项强，气血不能流通，须有虚灵自然之意。非有虚灵顶劲，则精神不能提起也。
* 含胸拔背
含胸者，胸略内涵，使气沉于丹田也。胸忌挺出，挺出则气拥胸 际，上重下轻，脚跟易于浮起。拔背者，气贴于背也，能含胸则自能拔背， 能拔背则能力由脊发，所向无敌也。
* 松腰
腰为一身之主宰，能松腰然后两足有力，下盘稳固；虚实变化皆由腰 转动，故曰：“命意源头在腰际”，由不得力必于腰腿求之也。
* 分虚实
太极拳术以分虚实为第一义，如全身皆坐在右腿，则右腿为实，左 腿为虚；全身皆坐在左腿，则左腿为实，右腿为虚。虚实能分，而后转动 轻灵，毫不费力；如不能分，则迈步重滞，自立不稳，而易为人所牵动。
* 沉肩坠肘
沉肩者，肩松开下垂也。若不能松垂，两肩端起，则气亦随之而 上，全身皆不得力矣。坠肘者，肘往下松垂之意，肘若悬起，则肩不能沉， 放人不远，近于外家之断劲矣。
* 用意不用力
太极拳论云：此全是用意不用力。练太极拳全身松开，不便有 分毫之拙劲，以留滞于筋骨血脉之间以自缚束，然后能轻灵变化，圆转自 如。或疑不用力何以能长力？盖人身之有经络，如地之有沟壑，沟壑不塞 而本行，经络不闭则气通。如浑身僵劲满经络，气血停滞，转动不灵，牵 一发而全身动矣。若不用力而用意，意之所至，气即至焉，如是气血流注， 日日贯输，周流全身，无时停滞。久久练习，则得真正内劲，即太极拳论 中所云:“极柔软，然后极坚刚”也。太极拳功夫纯熟之人，臂膊如绵裹 铁，分量极沉；练外家拳者，用力则显有力，不用力时，则甚轻浮，可见 其力乃外劲浮面之劲也。不用意而用力，最易引动，不足尚也。
* 上下相随
上下相随者，即太极拳论中所云:其根在脚，发于腿，主宰于腰， 形于手指，由脚而腿而腰，总须完整一气也。手动、腰动、足动，眼神亦 随之动，如是方可谓之上下相随。有一不动，即散乱也。
* 内外相合
太极拳所练在神，故云：“神为主帅，身为驱使”。精神能提得 起，自然举动轻灵。架子不外虚实开合;所谓开者，不但手足开，心意亦 与之俱开，所谓合者，不但手足合，心意亦与之俱合，能内外合为一气， 则浑然无间矣。
* 相连不断
外家拳术，其劲乃后天之拙劲，故有起有止，有线有断，旧力巳 尽，新力未生，此时最易为人所乘。太极拳用意不用力，自始至终，绵绵 不断，周而复始，循环无穷。原论所谓“如长江大河，滔滔不绝”，又日 “运劲如抽丝”，皆言其贯串一气也。
* 动中求静
外家拳术，以跳掷为能，用尽气力，故练习之后，无不喘气者。 太极拳以静御动，虽动犹静，故练架子愈慢愈好。使则呼吸深长，气沉丹 田，自无血脉愤张之弊。学者细心休会，庶可得其意焉。
