#+TITLE: 杨澄甫传抄太极拳谱
#+LANGUAGE: cn
#+DESCRIPTION: 杨澄甫传抄太极拳谱
#+KEYWORDS:  杨澄甫 太极拳
#+OPTIONS: toc:1
#+LINK_HOME: ../index.html

* 太极平准腰顶解

顶为准头，故曰顶头悬也；两手即左右之盘也，腰即根株也；立如平准，有平准
在身，则所谓轻重浮沉，分厘丝毫，莫不显然可辨矣。有平准之顶头悬(乃是从
头顶至腰之根株下，胸门至尾闾间为一条线).

歌曰：上下一条线，全凭两手转，变化取分毫，尺寸自己辨，车轮两命门，一纛
摇又转。心令气旗使，自然随我便，满身轻利者，金刚罗汉炼，对待有往来，是
早或是晚，合则发放去，不必凌霄箭。涵养知多少，一气哈而迷，口授须秘传，
开门见中天。

* 太极正功解
太极者圆也，无论内外上下左右，不离此圆也。太极者方也，无论内外上下左右，不离此方也。圆之出入，方之进退，随方就圆之往来，方为开展，圆为紧凑。
方圆规矩之至，孰能出此以外哉。如此得心应手，仰高钻坚，神乎其神，是隐显微，明而且明，生生不已，欲罢不能。

* 太极轻重浮沉解
  + 双重为病，病于填实，与沉之不同也。
  + 双沉不为病，自尔腾虚，与重之不一也。
  + 双浮为病，病为漂渺，与轻之不例也。
  + 双轻不为病，天然轻灵，与浮之不等也。
  + 半轻半重不为病，半者，半有着落，所以不为病。
  + 偏轻偏重为病，偏者，偏无着落，所以为病。因无着落，必失方圆；半有着落，岂出方圆。
  + 半浮半沉为病，失之不及也。
  + 偏浮偏沉为病，失之太过也。
  + 半重偏重为病，滞而不正也。
  + 半轻偏轻为病，灵而不圆也。
  + 半沉偏沉为病，虚而不正也。
  + 半浮偏浮为病，茫而不圆也。
  + 夫双轻不近于浮，则为轻灵；双沉不近于重，则为离虚。

故曰上手轻重，半有着落，则为平手。除此三者之外，皆为病手，盖内之虚灵不
昧，自然致于外，则清明在躬，流行于肢体间矣。若不穷研轻重浮沉之手，有掘
井徒劳不及泉之叹。然方圆四正之手，能表里精粗无不到者，则已及大成，又何
虑有四隅以出方圆乎。亦即所谓"方而圆"，"圆而方"，超乎象外，得其寰中之上
手也。

* 太极力气解
气走于膜络筋脉，力出于血肉皮骨。故有力者外壮于皮骨，形也；有气者内壮于
筋脉，象也。气血功于内壮，血气功于外壮。要之，明于气血二字之功，能自知
力气所由来；知力气之所以然，自知用力行气之各异。盖行气于筋脉，用力于皮
骨，大不相侔也。

* 太极文武解
文者体也，武者用也。文功武用于精气神，谓之文体；武功得文体于心身，谓之武事。夫文武尤有火候之谓。
在"卷放"得其时中，文体之本，武事文为，乃属于柔软文体也。在"蓄发"适当其可者，武事之根，文事武用，乃属于坚刚武事也。精气神与筋骨，乃文事武用；若坚刚武事，乃心身内之骨力也。夫文无武之预备，是有体无用；武无文之伴侣，是有用无体。
独木难支，孤掌不鸣，不唯文体武事如此，天下事，事事皆如此理也。文者内理
也，武者外数也。有外数无内理，必为血气之勇，失去本来面目，欺敌必败；有
内理无外数，徒思安静之学，未知用以操战，差微则亡耳。自用及于人，文武二
字之解，岂可忽哉。

* 沾粘连随解
  + 提上拔高谓之沾，留恋缱绻谓之粘，
  + 舍己无离谓之连，彼走此应谓之随。
  + 要知人之知觉运动，非明沾粘连随不可，斯沾粘连随之功夫，亦甚细矣。

  + 顶匾丢抗解
  + 顶者出头之谓，匾者不及之谓，
  + 丢者离开之谓，抗者太过之谓。

要知此四字之病，不但沾粘连随之功断，且不明知觉运动矣，初学者不可不知，更不可不去此四病，所难在沾粘连随中不许顶匾丢抗，是所不易也。

* 对待无病
顶匾丢抗失之对待也，所以谓之病，既失沾粘连随，何能得到知觉运动?既不能
知之于己，焉能知人?所谓对待无病者，乃不以顶匾丢抗对待于人，要以沾粘连
随对待于人耳。能如是，不但无病，知觉运动自然得之，可以进于懂劲之功矣。

* 对待用功法守中土歌
定之方中足有根，先明四正进退身，掤履挤按自四手，须费功夫得其真。身形腰
顶皆可以，沾粘连随意气君，运动知觉来相应，神是君位骨肉臣。分明火候七十
二，天然乃武并乃文。

* 太极圈歌
退圈容易进圈难，不离腰顶后与前，所难中土不离位，退易进难仔细研，此为动
功非站定，以身进退并比肩，能如水磨动急缓，云龙风虎像周旋，要用天盘从此
觅，久而久之出天然。

* 太极四隅解
四正，四方也，所谓掤履挤按是也。初不知方能使圆，方圆复始之理，生生不
已，焉有出隅之手哉。缘人外之肢体，内之神气，甚难得方圆四正之功，始出轻
重浮沉之病，则有隅矣。例如半重偏重之滞而不正，自出采挒肘靠之隅手，或双
重填实，亦出隅手也。

病多之手，不得已以隅手扶之，使复归于方正圆中之内，采用肘靠者，亦由此以
补其缺尔。夫日后功夫能至上乘者，亦须获采挒之功，使之仍归大中至正，是则
四隅之用，乃扶体而补其缺者也。

* 太极武事解
太极武事，外操柔软，内含坚刚，常求柔软之于外，久之自可得内之坚刚，非有
心之坚刚，实有心之柔软也。所难者内要坚刚而不施于外，终柔软以迎敌，即以
柔软而迎坚刚，使坚刚化为乌有耳。曰，何以致之哉?其要，非沾粘连随之功已
成，由于知觉运
动得之后，进为懂劲，懂劲后自可阶及神明之化境，最后当可完成而致之矣。

夫四两拨千斤之妙，倘功不及化境，将何以能?是则懂得沾粘连随后，乃能得其
视听轻灵之功耳。

* 太极懂劲先后论
夫未懂劲之先，常出顶匾丢抗之病；既懂劲之后，又恐出俯仰断续之病。既未懂
劲，固然出病手；既已懂劲，何以又出病手?盖劲似懂未懂之际，正在两可，断
接无准，故出病；神明尚犹不及，俯仰无着落，亦易出病；若不出"断接俯仰"，
非真懂劲，不能
不出此病也。

故未真懂者，乃由视听无由，未得其确耳，如知：
瞻、眇、顾、盼之视觉，起、落、缓、急之听知，闪、还、撩、了之运觉，转、
换、进、退之动知，是为真懂劲。

懂劲后自可阶及神明，自得屈伸进退之妙，如此屈伸动静，开合升降，自有由矣。
由屈伸动静，见入则开，遇出则合，观来则降，就去则升。夫而后才能真及神明
矣。明乎此，日后岂可不慎行坐卧走站、饮食溺溷之功，以协进其效，是则可谓
将及中成大成也哉。

* 太极尺寸分毫解
功夫先练开展，后练紧凑，开展成而得之，才讲紧凑，紧凑成功后，才讲尺寸分
毫。盖尺位之功成，而后能以寸位分，寸位功成后以分位分；分位功成后，以毫
位分。此所谓尺寸分毫之理也明矣。然尺必十寸，寸必十分，分必十毫，其数在
焉。古云：对待者数也。知其数则能得尺寸分毫，然而虽知其数，苟非有秘传，
又安能量之哉。
